config/routes.rb
Workwiki::Application.routes.draw do
  root to: "static_pages#index"
  resources :users, except: [:edit, :update] do
    collection do
      get 'bulk_new', to: 'users#bulk_new'
      post 'bulk_add', to: 'users#bulk_add'
      get 'add_more', to: 'users#add_more'
      get 'valid_email', to: 'users#valid_email'
    end
  end

  resources :companies, only: [:new, :create, :destroy]
  post "start", to: "companies#start"
  resource :session, only: [:new, :create, :destroy]
  resources :subdivisions
  resources :subdivision_managements, only: [:new, :create, :destroy]
  resources :words do
    resources :definitions, only: [:create, :index]
  end

  resources :definitions, only: [:edit, :destroy, :update, :create] do
    member do
      post 'upvote', :to => 'votes#create_upvote'
      post 'downvote', :to => 'votes#create_downvote'
      delete 'upvote', :to => 'votes#destroy_upvote'
      delete 'downvote', :to => 'votes#destroy_downvote'
      get 'email', :to => 'definitions#new_email_definition'
      post 'favorite', to: 'definition_faves#favorite'
      delete 'unfavorite', to: 'definition_faves#unfavorite'
      post 'add_to_curriculum', to: 'definitions#add_to_curriculum'
    end
  end

  resources :votes, only: [:upvote, :downvote]
  resources :tags
  resources :curriculums do
    member do
      post 'email', to: 'curriculums#email'
      post 'favorite', to: 'curriculum_faves#favorite'
      delete 'unfavorite', to: 'curriculum_faves#unfavorite'
    end
  end
  resources :curriculum_definitions, only: [:create, :destroy, :new]
  resources :messages do
    collection do
      get 'sent', :to => 'messages#sent_index'
    end
  end

  get 'favorites', to: 'users#favorites'
  get 'forgot_password', to: 'users#forgot_password'
  post 'send_forgot_password_email', to: 'users#send_forgot_password_email'
  get 'set_new_password', to: 'users#set_new_password'
  post 'update_password', to: 'users#update_password'
  resource :search, only: [:new, :create, :destroy]
  get 'notify_recipient', to: 'inbound#notify_recipient'

  resources :static_pages, only: [:index]
  get 'invite', to: 'invites#new'
  post 'invite', to: 'invites#create'
  get 'invite/rsvp', to: 'invites#rsvp'
  get 'account', to: 'users#edit'
  put 'account/update', to: 'users#update'
  get 'invite/employees', to: 'invites#new_employees'
  post 'invite/employees', to: 'invites#create_employees'
  get '/signup', to: 'invites#employee_signup'
  get '/offer', to: 'static_pages#offer'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	before_filter :require_current_user!

	def index
		@new_words = Word.recently_added(current_co, 5)
		@new_curriculums = Curriculum.recently_added(current_co, 5)
		@new_definitions = Definition.recently_added(current_co, 3)
		@tags = Tag.where('company_id = ?', current_co.id)
		@subdivisions = Subdivision.where('company_id = ?', current_co.id)
		render :index
	end

	def offer
		render :offer, layout: "sales"
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<script type="text/javascript">
    mixpanel.register({
        "user": "<%= current_user.email %>"
    });
</script>
<div class="content">
	<div class="content-boxes">
		<div class="content-box">
			<div class="content-box-pic">
				<%= image_tag "new-curriculum.png", size: "128x128" %>
			</div>
			<div class="content-box-text">
				<h3>
					New Curriculums
				</h3>
				<ul>
					<% @new_curriculums.each do |curriculum| %>
						<li>
							<%= link_to curriculum.name, curriculum_url(curriculum.id) %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="content-box">
			<div class="content-box-pic">
				<%= image_tag "new-definition.png", size: "128x128" %>
			</div>
			<div class="content-box-text">
				<h3>
					New Definitions
				</h3>
				<ul>
					<% @new_definitions.each do |definition| %>
						<li>
							<%= link_to definition.word.name, word_url(definition.word.id) %>
							<br>
							<%= definition.body[0..45].gsub(/\s\w+\s*$/, '...') %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="content-box">
			<div class="content-box-pic">
				<%= image_tag "new-word.png", size: "128x128" %>
			</div>
			<div class="content-box-text">
				<h3>
					New Words
				</h3>
				<ul>
					<% @new_words.each do |word| %>
						<li>
							<%= link_to word.name, word_url(word.id) %>
						</li>
					<% end %>
				</ul>
				</p>
			</div>
		</div>
	</div>
	<div class="add-words-box group">
		<p class="add-words-text">
			Did you learn a new word and want to share it with your teammates?  Add the word!  If you heard a new word, but don't know the definition, add the word and if one of your colleagues knows the definition they will help you out by adding the definition.
		</p>
		<div class="add-words-button">
			<button id="add-cta" class="add-word" data-id="add-word-modal">
				Add a Word
			</button>
		</div>
	</div>
</div>
<div class="add-word-modal hidden">
  <div class="form">
  	<div class="word">
  		<label for="word_name"><h2>Word</h2></label>
  		<input type="text" id="word_name" name="word[name]" placeholder="Type word here">
  	</div>
    <div class="definition_body">
      <label for="definition_body"><h2>Definition</h2></label>
      <textarea name="definition[body]" id="definition_body" type="text" placeholder="Type definition here"></textarea>
    </div>
    <div class="example">
      <label for="example_body"><h3>Example (optional)</h3></label>
      <textarea name="example[body]" id="example_body" placeholder="Type example here"></textarea>
    </div>
     <div class="subdivisions">
      <label for="subdivision_id"><h3>Department (optional)</h3></label>
      <select name="subdivision_id" id="subdivision_id">
        <option value="0">Uncategorized</option>
        <% @subdivisions.each do |subdivision| %>
          <option value="<%= subdivision.id %>"><%= subdivision.name %></option>
        <% end %>
      </select>
    </div>
    <div class="tags">
      <label for="definition_tag_ids"><h3>Tags (optional)</h3></label>
      <select name="definition[tag_ids][]" multiple data-placeholder="Select Tags" id="definition_tag_ids">
        <% @tags.each do |tag| %>
          <option value="<%= tag.id %>"><%= tag.name %></option>
        <% end %>
      </select>
    </div>
    <div class="actions">
      <span class="cancel">
        <a href="#" data-id="add-word-modal">Cancel</a>
      </span>
      <button id="add-cta" class="submit-word">
        Add
      </button>
    </div>
  </div>
</div>

app/views/static_pages/offer.html.erb
<div class="top">  
  <div class="nav group">
    <div class="nav-left-offer">
      <div class="logo">
        <p>
          <%= link_to 'Rampup Ready', root_url %>
        </p>
      </div>
    </div>
    <div class="nav-right-offer group">
      <div class="sign-up-text">
        Start your FREE trial today
      </div>
      <div class="sign-up-form">
        <input type="text" placeholder="Enter your email address">
        <button>Sign Up</button>
      </div>
      <%= link_to "Log In", new_session_url %>
    </div>
  </div>
</div>
<div class="content">
  <div class="headline">
    <h1>
      Help your employees get ramped up so they can do their job from day one.
    </h1>
    <br>
    <p>
      Rampup Ready is a private and interactive glossary your employees will use to learn industry and company terminology that they hear on a day-to-day basis.
    </p>
  </div>
  <div class="testimonials">
    <div class="content-boxes">
    <div class="content-box">
      <div class="content-box-pic">
        <%= image_tag "testimonial-placeholder-1.jpg", size: "128x128", class: "testimonial" %>
      </div>
      <div class="content-box-text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
    <div class="content-box">
      <div class="content-box-pic">
        <%= image_tag "testimonial-placeholder-2.jpg", size: "128x128", class: "testimonial" %>
      </div>
      <div class="content-box-text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
    <div class="content-box">
      <div class="content-box-pic">
        <%= image_tag "testimonial-placeholder-3.jpg", size: "128x128", class: "testimonial" %>
      </div>
      <div class="content-box-text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
  <hr>
  <div class="benefits">
    <div class="benefits-headline">
      <h1>
        A glossary is only useful if it is scalable, organized<br>and engaging.
      </h1>
    </div>
    <div class="benefit-statements">
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          Content is searchable and automatically organized so that it never becomes overwhelming to maintain.
        </div>
      </div>
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          A centralized glossary helps everyone speak the same language and keeps all employees up to date.
        </div>
      </div>
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          Leaderboards and badges for the most active employees makes education fun and engages employees.
        </div>
      </div>
    </div>
  </div>
  <div class="walkthrough">
    <div class="feature group">
      <div class="feature-left">
        <%= image_tag "invite2.png", class: "feature-img" %>
      </div>
      <div class="feature-right">
        <div class="feature-text">
          <h1>Make learning scalable.</h1>
          <br>
          <p>
            Invite champions from different departments to contribute words and definitions that the rest of the company needs to know.  Invite all or as many employee as you need.
          </p>
        </div>
      </div>
    </div>
    <div class="feature group">
      <div class="feature-left">
        <div class="feature-text">
          <h1>Know exactly where your employees are struggling.</h1>
          <br>
          <p>
            Get reports on how your employees are using the glossary including frequently searched words.
          </p>
        </div>
      </div>
      <div class="feature-right">
        <%= image_tag "graphs.png", class: "feature-img", size: "500x315" %>
      </div>
    </div>
    <div class="feature group">
      <div class="feature-left">
        <%= image_tag "curriculum2.png", class: "feature-img" %>
      </div>
      <div class="feature-right">
        <div class="feature-text">
          <h1>New employees are more prepared on day one.</h1>
          <br>
          <p>
            Use the curriculum builder to create a curriculum of words and definitions that a new hire can use on day one.
          </p>
        </div>
      </div>
    </div>
    <div class="feature group">
      <div class="feature-left">
        <div class="feature-text">
          <h1>Employees become their client's most knowledgeable partner.</h1>
          <br>
          <p>
            All the definitions are quickly searchable.
          </p>
        </div>
      </div>
      <div class="feature-right">
        <%= image_tag "search.png", class: "feature-img", size:"500x300"%>
      </div>
    </div>
    <div class="feature group">
      <div class="feature-left">
        <%= image_tag "adddefinition.png", class: "feature-img" %>
      </div>
      <div class="feature-right">
        <div class="feature-text">
          <h1>Employees can help each other.</h1>
          <br>
          <p>
            Many terms have different definitions.  Provide all the definitions and let your employees vote on which ones are most applicable.
          </p>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="what-you-get">
    <div class="what-you-get-headline">
      <h1>Are you ready to ramp up your team?</h1>
      <br>
      <p>
        Here's what you get:
      </p>
    </div>
    <div class="benefit-statements">
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          A private company glossary for your team to add as many words and definitions as you need.
        </div>
      </div>
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          As many user accounts as your company needs.
        </div>
      </div>
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          Reports sent to you with usage data, like the most searched words or topics.
        </div>
      </div>
      <div class="benefit-statement group">
        <div class="benefit-icon">
          <%= image_tag "add.png", size: "16x16" %>
        </div>
        <div class="benefit-content">
          A curriculum builder to create a guide for new and existing employees.
        </div>
      </div>
    </div>
  </div>
  <div class="sign-up-offer">
    <div class="sign-up-offer-headline">
      <h1>Start your free trial today.</h1>
      <br>
      <p>
        You get a free 50-word glossary forever.  For more words, it costs only $5 per user/month.
      </p>
    </div>
    <div class="bottom-sign-up-form">
      <form action="<%= start_url %>" method="post">
        <input type="text" placeholder="Enter your email address" name="user[email]">
        <button id="add-cta">Sign Up</button>
      </form>
    </div>
  </div>
</div>