config/routes.rb
Workwiki::Application.routes.draw do
  root to: "static_pages#index"
  resources :users, except: [:edit, :update] do
    collection do
      get 'bulk_new', to: 'users#bulk_new'
      post 'bulk_add', to: 'users#bulk_add'
      get 'add_more', to: 'users#add_more'
      get 'valid_email', to: 'users#valid_email'
    end
  end

  resources :companies, only: [:new, :create, :destroy]
  post "start", to: "companies#start"
  resource :session, only: [:new, :create, :destroy]
  resources :subdivisions
  resources :subdivision_managements, only: [:new, :create, :destroy]
  resources :words do
    resources :definitions, only: [:create, :index]
  end

  resources :definitions, only: [:edit, :destroy, :update, :create] do
    member do
      post 'upvote', :to => 'votes#create_upvote'
      post 'downvote', :to => 'votes#create_downvote'
      delete 'upvote', :to => 'votes#destroy_upvote'
      delete 'downvote', :to => 'votes#destroy_downvote'
      get 'email', :to => 'definitions#new_email_definition'
      post 'favorite', to: 'definition_faves#favorite'
      delete 'unfavorite', to: 'definition_faves#unfavorite'
      post 'add_to_curriculum', to: 'definitions#add_to_curriculum'
    end
  end

  resources :votes, only: [:upvote, :downvote]
  resources :tags
  resources :curriculums do
    member do
      post 'email', to: 'curriculums#email'
      post 'favorite', to: 'curriculum_faves#favorite'
      delete 'unfavorite', to: 'curriculum_faves#unfavorite'
    end
  end
  resources :curriculum_definitions, only: [:create, :destroy, :new]
  resources :messages do
    collection do
      get 'sent', :to => 'messages#sent_index'
    end
  end

  get 'favorites', to: 'users#favorites'
  get 'forgot_password', to: 'users#forgot_password'
  post 'send_forgot_password_email', to: 'users#send_forgot_password_email'
  get 'set_new_password', to: 'users#set_new_password'
  post 'update_password', to: 'users#update_password'
  resource :search, only: [:new, :create, :destroy]
  get 'notify_recipient', to: 'inbound#notify_recipient'

  resources :static_pages, only: [:index]
  get 'invite', to: 'invites#new'
  post 'invite', to: 'invites#create'
  get 'invite/rsvp', to: 'invites#rsvp'
  get 'account', to: 'users#edit'
  put 'account/update', to: 'users#update'
  get 'invite/employees', to: 'invites#new_employees'
  post 'invite/employees', to: 'invites#create_employees'
  get '/signup', to: 'invites#employee_signup'
  get '/offer', to: 'static_pages#offer'
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :subject, :body, :sender_id, :recipient_id, :read

  validates :subject, :body, presence: true
  validates :read, :inclusion => {:in => [true, false]}

  belongs_to :sender
  belongs_to :recipient
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.find_all_by_recipient_id(current_user.id)
    render :index
  end

  def sent_index
    @messages = Message.find_all_by_sender_id(current_user.id)
    render :sent
  end

  def show
    @message = Message.find(params[:id])
    @sender = User.find(@message.sender_id)
    @recipient = User.find(@message.recipient_id)

    if is_current_user?(@message.recipient_id)
      @message.read = true
      @message.save
      render :show
    elsif is_current_user?(@message.sender_id)
      render :show
    else
      flash[:errors] = ["You are not authorized to view this message."]
      redirect_to new_session_url
    end
  end

  def new
    @message = Message.new
    @recipients = User.all
    render :new
  end

  def create
    params[:message][:sender_id] = current_user.id
    @message = Message.new(params[:message])
    if @message.save
      push_message(@message.recipient_id)
      if request.xhr?
        render :json => @message
      else
        msg = NotificationMailer.message_received_email(@message)
        msg.deliver!
        flash[:notice] = ["Message sent!"]
        redirect_to new_message_url
      end
    else
      if request.xhr?
        redirect_to words_url
      else
        flash[:errors] ||= []
        flash[:errors] += @message.errors.full_messages
        @recipients = User.all
        render :new
      end
    end
  end

  def destroy
  end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def unread_messages
    sum_new_messages = Message.find_all_by_recipient_id_and_read(current_user.id,false).count
    if sum_new_messages > 0
      return " (" + sum_new_messages.to_s + ")"
    else
      return ""
    end
  end

end

app/views/messages/_form.html.erb
<form action="<%= messages_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  From: <%= current_user.email %>
  <br>
  <label for="message_recipient_id">To:</label>
  <select name="message[recipient_id]">
    <% @recipients.each do |recipient| %>
      <%= selected = @message.recipient_id == recipient.id ? "selected" : "" %>
      <option value="<%= recipient.id %>" <%= selected.html_safe %>><%= recipient.email %></option>
    <% end %>
  </select>
   <br>
  <label for="message_subject">Subject:</label>
  <input type="text" id="message_subject" name="message[subject]" value="<%= @message.subject %>">
   <br>
  <label for="message_body">Body:</label>
  <textarea id="message_body" name="message[body]" rows="5" cols="50"><%= @message.body %></textarea>
   <br>
  <input type="Submit" value="Send Message">
</form>

app/views/messages/index.html.erb
<div class="received-messages-wrapper">
  <h2>Received Messages</h2>
  <ul>
    <% @messages.each do |message| %>
    <% status = message.read ? "read" : "unread" %>
      <li>
        <%= link_to message.subject, message_url(message.id) %> from <%= User.find(message.sender_id).email %>
        <%= time_ago_in_words(message.created_at) %> ago (<%= status.html_safe %>)
      </li>
    <% end %>
  </ul>
</div>

app/views/messages/new.html.erb
<div class="new-message-wrapper">
  <h2>Compose Message</h2>
  <%= render 'messages/form' %>
</div>

app/views/messages/sent.html.erb
<div class="sent-messages-wrapper">
  <h2>Sent Messages</h2>
  <ul>
    <% @messages.each do |message| %>
      <li>
        Subject: <%= link_to message.subject, message_url(message.id) %> | sent to <%= User.find(message.recipient_id).email %>
        <% if message.read %>
          (read)
        <% else %>
          (unread)
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/messages/show.html.erb
<div class="message-wrapper">
  <h2>Message</h2>
  From: <%= @sender.email %>
  <br>
  To: <%= @recipient.email %>
  <br>
  Subject: <%= @message.subject %>
  <br>
  Body: <%= @message.body %>
</div>