config/routes.rb
Workwiki::Application.routes.draw do
  root to: "static_pages#index"
  resources :users, except: [:edit, :update] do
    collection do
      get 'bulk_new', to: 'users#bulk_new'
      post 'bulk_add', to: 'users#bulk_add'
      get 'add_more', to: 'users#add_more'
      get 'valid_email', to: 'users#valid_email'
    end
  end

  resources :companies, only: [:new, :create, :destroy]
  post "start", to: "companies#start"
  resource :session, only: [:new, :create, :destroy]
  resources :subdivisions
  resources :subdivision_managements, only: [:new, :create, :destroy]
  resources :words do
    resources :definitions, only: [:create, :index]
  end

  resources :definitions, only: [:edit, :destroy, :update, :create] do
    member do
      post 'upvote', :to => 'votes#create_upvote'
      post 'downvote', :to => 'votes#create_downvote'
      delete 'upvote', :to => 'votes#destroy_upvote'
      delete 'downvote', :to => 'votes#destroy_downvote'
      get 'email', :to => 'definitions#new_email_definition'
      post 'favorite', to: 'definition_faves#favorite'
      delete 'unfavorite', to: 'definition_faves#unfavorite'
      post 'add_to_curriculum', to: 'definitions#add_to_curriculum'
    end
  end

  resources :votes, only: [:upvote, :downvote]
  resources :tags
  resources :curriculums do
    member do
      post 'email', to: 'curriculums#email'
      post 'favorite', to: 'curriculum_faves#favorite'
      delete 'unfavorite', to: 'curriculum_faves#unfavorite'
    end
  end
  resources :curriculum_definitions, only: [:create, :destroy, :new]
  resources :messages do
    collection do
      get 'sent', :to => 'messages#sent_index'
    end
  end

  get 'favorites', to: 'users#favorites'
  get 'forgot_password', to: 'users#forgot_password'
  post 'send_forgot_password_email', to: 'users#send_forgot_password_email'
  get 'set_new_password', to: 'users#set_new_password'
  post 'update_password', to: 'users#update_password'
  resource :search, only: [:new, :create, :destroy]
  get 'notify_recipient', to: 'inbound#notify_recipient'

  resources :static_pages, only: [:index]
  get 'invite', to: 'invites#new'
  post 'invite', to: 'invites#create'
  get 'invite/rsvp', to: 'invites#rsvp'
  get 'account', to: 'users#edit'
  put 'account/update', to: 'users#update'
  get 'invite/employees', to: 'invites#new_employees'
  post 'invite/employees', to: 'invites#create_employees'
  get '/signup', to: 'invites#employee_signup'
  get '/offer', to: 'static_pages#offer'
end

app/views/shared/_comma.html.erb
,

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
<title>RampUpReady.com</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<% if current_user %>
  <script type="text/javascript">
    mixpanel.identify("<%= current_user.id %>")
    mixpanel.people.set({
      "$email": "<%= current_user.email %>",
      "$created": "<%= current_user.created_at %>"
    });
  </script>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="top-header group">
    <div class="top-header-left">
      <div class="logo">
        <%= link_to image_tag("rampuprev_cropped.png"), root_url %>
      </div>
    </div>
    <div class="top-header-right">
      <div class="sign-in-up-out">
        <% if user_logged_in %>
          <!-- <p>Hi, <%= current_user.email %>!</p> -->
          <%= button_to "Log Out", session_url, method: :delete, class: "submit" %>
        <% else %>
          <%= link_to "Log In", new_session_url %> | <%= link_to "Sign Up", new_user_url %>
        <% end %>
      </div>
      <div class="search">
        <form action="<%= search_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="text" name="keyword" style="width: 200px;">
          <input type="Submit" class="submit" value="Search">
        </form>
      </div>
    </div>
  </div>
  <div class="bottom-header group">
    <nav>
      <ul class="group">
        <li><%= link_to "Words", words_url %></li>
        <li><%= link_to "Subdivisions", subdivisions_url %></li>
        <li><%= link_to "Curriculums", curriculums_url %></li>
        <li><%= link_to "Tags", tags_url %></li>
        <li><%= link_to "Add Users", bulk_new_users_url %></li>
        <% if user_logged_in %>
          <li class="nav-bar-inbox"><%= link_to "Inbox" + unread_messages, messages_url %></li>
  		    <li><%= link_to "Favorites", favorites_url %></li>
        <% end %>
      </ul>
      <div class="bottom-nav hidden">
        <ul class="inbox-options group">
			    <li><%= link_to "Compose New Message", new_message_url, id: "compose-new-message" %></li>
  				<li><%= link_to "Received Messages", messages_url %></li>
          <li><%= link_to "Sent Messages", sent_messages_url %></li>
  			</ul>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_notices.html.erb
<% if flash[:notice] %>
  <% flash[:notice].each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_top.html.erb
<div class="top">  
  <div class="nav group">
    <div class="nav-left">
      <div class="logo">
        <p>
          <%= link_to 'Rampup Ready', root_url %>
        </p>
      </div>
      <div class="links">
        <ul>
          <% if current_user %>
            <li><%= link_to 'Words', words_url %></li>
            <li><%= link_to 'Curriculums', curriculums_url %></li>
            <li><%= link_to 'Favorite Definitions', favorites_url %></li>
            <li><%= link_to 'Invite Employees', invite_employees_url if current_user.admin %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="nav-right">
      <div class="user-info">
        <div class="name">
          <%= link_to current_user.email, account_url if current_user %>
        </div>
        <div class="avatar">
          <!-- <%= image_tag "user-4.png" %> -->
          <% if current_user %>
            <%= button_to "Log Out", session_url, method: :delete, class: 'log-out' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>