config/routes.rb
Workwiki::Application.routes.draw do
  root to: "static_pages#index"
  resources :users, except: [:edit, :update] do
    collection do
      get 'bulk_new', to: 'users#bulk_new'
      post 'bulk_add', to: 'users#bulk_add'
      get 'add_more', to: 'users#add_more'
      get 'valid_email', to: 'users#valid_email'
    end
  end

  resources :companies, only: [:new, :create, :destroy]
  post "start", to: "companies#start"
  resource :session, only: [:new, :create, :destroy]
  resources :subdivisions
  resources :subdivision_managements, only: [:new, :create, :destroy]
  resources :words do
    resources :definitions, only: [:create, :index]
  end

  resources :definitions, only: [:edit, :destroy, :update, :create] do
    member do
      post 'upvote', :to => 'votes#create_upvote'
      post 'downvote', :to => 'votes#create_downvote'
      delete 'upvote', :to => 'votes#destroy_upvote'
      delete 'downvote', :to => 'votes#destroy_downvote'
      get 'email', :to => 'definitions#new_email_definition'
      post 'favorite', to: 'definition_faves#favorite'
      delete 'unfavorite', to: 'definition_faves#unfavorite'
      post 'add_to_curriculum', to: 'definitions#add_to_curriculum'
    end
  end

  resources :votes, only: [:upvote, :downvote]
  resources :tags
  resources :curriculums do
    member do
      post 'email', to: 'curriculums#email'
      post 'favorite', to: 'curriculum_faves#favorite'
      delete 'unfavorite', to: 'curriculum_faves#unfavorite'
    end
  end
  resources :curriculum_definitions, only: [:create, :destroy, :new]
  resources :messages do
    collection do
      get 'sent', :to => 'messages#sent_index'
    end
  end

  get 'favorites', to: 'users#favorites'
  get 'forgot_password', to: 'users#forgot_password'
  post 'send_forgot_password_email', to: 'users#send_forgot_password_email'
  get 'set_new_password', to: 'users#set_new_password'
  post 'update_password', to: 'users#update_password'
  resource :search, only: [:new, :create, :destroy]
  get 'notify_recipient', to: 'inbound#notify_recipient'

  resources :static_pages, only: [:index]
  get 'invite', to: 'invites#new'
  post 'invite', to: 'invites#create'
  get 'invite/rsvp', to: 'invites#rsvp'
  get 'account', to: 'users#edit'
  put 'account/update', to: 'users#update'
  get 'invite/employees', to: 'invites#new_employees'
  post 'invite/employees', to: 'invites#create_employees'
  get '/signup', to: 'invites#employee_signup'
  get '/offer', to: 'static_pages#offer'
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: { message: "of company or organization can't be blank" }
  before_validation :ensure_signup_token

  has_many(
  	:subdivisions,
  	class_name: "Subdivision",
  	foreign_key: :company_id,
  	primary_key: :id,
  	inverse_of: :company
	)

  has_many :words
  has_many :tags
  has_many :curriculums
  has_many :definitions

  def self.generate_signup_token
    SecureRandom.urlsafe_base64(16)
  end

  private

  def ensure_signup_token
    self.signup_token ||= self.class.generate_signup_token
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new
		render :new, layout: "sales"
	end

	def start
		@email = params[:user][:email]
		render :new, layout: "sales"
	end

	def create
		@company = Company.new(params[:company])
		@subdivision = @company.subdivisions.new(name: "General")
		params[:user][:admin] = true
		@user = @subdivision.employees.new(params[:user])

		if @company.save
			log_user_in!(@user, invite_url)
		else
			all_errors = []
			@company.errors.messages.except!(:subdivisions)
			all_errors = all_errors + @company.errors.full_messages + @user.errors.full_messages
      # render json: all_errors, status: 422
      flash.now[:errors] = all_errors
      render :new, layout: "sales"
		end
	end

	def destroy
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/new.html.erb
<%= render 'shared/top' %>
<div class="signup-container">
	<div class="signup-header">
		<h1>Start your FREE trial today.</h1>
		<h3>You get a free 50-word glossary, forever.  For more words, it costs only $5 per user/month.</h3>
	</div>
	<div class="company-signup-form-container">
		<div class="company-signup-errors">
			<% if flash[:errors] %>
		    <ul>
		      <% flash[:errors].each do |msg| %>
		        <li>
		          <%= msg %>
		        </li>
		      <% end %>
		    </ul>
		  <% end %>
		</div>
		<div class="company-signup-form group">
			<form action="<%= companies_url %>" method="post" id="company-signup">
				<label for="user_email">Your email address:</label>
				<br>
				<input type="text" name="user[email]" id="user_email" value="<%= @email if @email %>">
				<br>
				<label for="user_password">Your password:</label>
				<br>
				<input type="password" name="user[password]" id="user_password">
				<br>
				<label for="user_name">Your full name:</label>
				<br>
				<input type="text" name="user[name]" id="user_name">
				<br>
				<label for="company_name">Company or Organization:</label>
				<br>
				<input type="text" name="company[name]" id="company_name">
				<br>
				<button id="add-cta">Start my free trial</button>
			</form>
		</div>
	</div>
</div>